name: Release Go Library

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-go-library:
    uses: slice-soft/ss-pipeline/.github/workflows/release-go-library.yml@v0
    with:
      module: github.com/slice-soft/ss-keel-redis
    secrets: inherit
